language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
    - build

jobs:
  include:
    - stage: bundle
      script: npm install
    - stage: test
      script: npm test
    - stage: build
      script: npm build
    - stage: deploy
      deploy:
        provider: surge
        env: SURGE_TOKEN=83ba5b1205be8b153eda8db28b8bbe03
        skip_cleanup: true
        domain: chamada-test.surge.sh
        project: ./build/
        on:
          all_branches: true

