language: node_js
node_js:
  - 12
sudo: false
cache:
  directories:
    - node_modules
    - build

jobs:
  include:
    - stage: test and build
      script: npm install && npm run test && npm run-script build
    - stage: deploy
      deploy:
        provider: surge
        skip_cleanup: true
        domain: chamada-test.surge.sh
        project: ./build/
        on:
          all_branches: true

