language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
    - build

jobs:
  include:
    # - stage: bundle
    #   script: npm install 
    - stage: test
      script: npm install && npm run test
    - stage: build
      script: npm run-script build
    - stage: deploy
      deploy:
        provider: surge
        skip_cleanup: true
        domain: chamada-test.surge.sh
        project: ./build/
        on:
          all_branches: true

