language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: chamada-test.surge.sh
  project: ./build/
on:
  all_branches: true
